package Acme::CPANLists::Import::PerlDancerAdvent::2011_12_17;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2011/17] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"CHI"},{module=>"DBI"},{module=>"DBIx::Class"},{module=>"Dancer::Plugin::Ajax"},{module=>"Dancer::Plugin::Cache::CHI"},{module=>"Dancer::Plugin::DBIC"},{module=>"Dancer::Plugin::Database"},{module=>"Dancer::Plugin::Email"},{module=>"Dancer::Plugin::EscapeHTML"},{module=>"Dancer::Plugin::Facebook"},{module=>"Dancer::Plugin::Mongo"},{module=>"Dancer::Plugin::Passphrase"},{module=>"Dancer::Plugin::Redis"},{module=>"Dancer::Plugin::SMS"},{module=>"Dancer::Plugin::SimpleCRUD"},{module=>"Dancer::Plugin::Stomp"},{module=>"Dancer::Plugin::Thumbnail"},{module=>"Email::Send"},{module=>"Facebook::Graph"},{module=>"GD"},{module=>"MongoDB"},{module=>"Net::Stomp"},{module=>"SMS::Send"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2011 (day 17)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2011 (day 17)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2011/17> (retrieved on 2016-11-24). Visit the URL for the full contents.

