package Acme::CPANLists::Import::PerlDancerAdvent::2011_12_18;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2011/18] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Dancer::Template::Abstract"},{module=>"Dancer::Template::Haml"},{module=>"Dancer::Template::Mason"},{module=>"Dancer::Template::Simple"},{module=>"Dancer::Template::Tenjin"},{module=>"Dancer::Template::Tiny"},{module=>"Dancer::Template::Xslate"},{module=>"Template::Tiny"},{module=>"Text::Haml"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2011 (day 18)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2011 (day 18)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2011/18> (retrieved on 2016-11-24). Visit the URL for the full contents.

