package Acme::CPANLists::Import::PerlDancerAdvent::2011_12_13;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2011/13] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Dancer::Plugin::Auth::Htpasswd"},{module=>"Dancer::Plugin::DirectoryView"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2011 (day 13)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2011 (day 13)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2011/13> (retrieved on 2016-11-24). Visit the URL for the full contents.

