package Acme::CPANLists::Import::PerlDancerAdvent::2011_12_16;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2011/16] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Dancer::Debug"},{module=>"Moose::Role"},{module=>"Plack"},{module=>"Plack::Builder"},{module=>"Plack::Middleware"},{module=>"Plack::Middleware::Debug"},{module=>"Plack::Middleware::Deflater"},{module=>"Plack::Middleware::ETag"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2011 (day 16)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2011 (day 16)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2011/16> (retrieved on 2016-11-24). Visit the URL for the full contents.

