package Acme::CPANLists::Import::PerlDancerAdvent::2011_12_03;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2011/3] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"DBD::SQLite"},{module=>"Dancer::Plugin::Database"},{module=>"Dancer::Plugin::SimpleCRUD"},{module=>"Dancer::Template::Simple"},{module=>"Plack::Handler::FCGI"},{module=>"Plack::Runner"},{module=>"Starman"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2011 (day 3)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2011 (day 3)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2011/3> (retrieved on 2016-11-24). Visit the URL for the full contents.

